spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:${DATABASE:mem}:${DATABASE_NAME:yatagarasu};DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_LOWER=TRUE
    username: 'sa'

  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: true